// subfolder/Jenkinsfile
def run() {
    pipeline {
        agent any

        stages {
            stage('Hello from Subfolder') {
                steps {
                    echo 'Hello from the Jenkinsfile in the subfolder!'
                }
            }
        }
    }
}
