pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "conkhipecpec/2048-jekins"
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello, World!'
            }
        }
    }
}
